config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/auth/github', as: :github_login

  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:username', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event
  attr_reader :type, :repo, :created_at

  def initialize(attrs)
    @type = attrs[:type]
    @repo = attrs[:repo][:name]
    @created_at = DateTime.parse(attrs[:created_at])
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :login,
              :uid,
              :name,
              :bio,
              :avatar,
              :public_repos,
              :following,
              :followers

  def initialize(attrs)
    @login = attrs[:login]
    @uid = attrs[:id].to_s
    @name = attrs[:name]
    @bio = attrs[:bio]
    @avatar = attrs[:avatar_url]
    @public_repos = attrs[:public_repos]
    @following = attrs[:following]
    @followers = attrs[:followers]
  end
end

app/models/repository.rb
class Repository
  attr_reader :name,
              :language, 
              :updated_at, 
              :forks_count, 
              :description, 
              :stargazers_count

  def initialize(attrs)
    @name = attrs[:name]
    @language = attrs[:language]
    @updated_at = DateTime.parse(attrs[:updated_at])
    @stargazers_count = attrs[:stargazers_count]
    @forks_count = attrs[:forks_count]
    @description = attrs[:description]
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |user|
      user.uid = auth_info.uid
      user.name = auth_info.extra.raw_info.name
      user.username = auth_info.extra.raw_info.login
      user.oauth_token = auth_info.credentials.token
      user.avatar = auth_info.extra.raw_info.avatar_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @profile = ProfilePresenter.new(params[:username])
    @profile.build_profile(params)
  end
end

app/controllers/welcome_controller.rb
require 'rss'

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_logged_out_nav.html.erb
<nav>
  <div class="main-menu">
    <div class="logo">
      <%= link_to image_tag('GitHub-Mark-Light-32px.png'), root_path %>
    </div>
    <div class="menu-links">
      <%= link_to 'Features', '/', class: 'menu-link' %>
      <%= link_to 'Business', '/', class: 'menu-link' %>
      <%= link_to 'Explore', '/', class: 'menu-link' %>
      <%= link_to 'Marketplace', '/', class: 'menu-link' %>
      <%= link_to 'Pricing', '/', class: 'menu-link' %>
    </div>
  </div>
  <%= form_tag('/', :method => "get") do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search GitHub', class: 'search' %>
  <% end %>
  <div class="sign-ins">
    <%= link_to 'Sign in', github_login_path, class: 'sign-in-link' %>
    <p id='sign-in-or'>or</p>
    <%= link_to 'Sign up', github_login_path, class: 'sign-in-link' %>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="main-menu">
    <div class="logo">
      <%= link_to image_tag('GitHub-Mark-Light-32px.png'), root_path %>
    </div>
    <%= form_tag('/', :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search GitHub', class: 'search logged-in' %>
    <% end %>
    <div class="menu-links main-links">
      <%= link_to 'Pull requests', '/', class: 'main-link' %>
      <%= link_to 'Issues', '/', class: 'main-link' %>
      <%= link_to 'Marketplace', '/', class: 'main-link' %>
      <%= link_to 'Explore', '/', class: 'main-link' %>
    </div>
  </div>
  <div class="sign-ins">
    <%= link_to image_tag('bell.svg'), github_login_path, class: 'notification-bell' %>
    <%= link_to image_tag('plus.svg'), github_login_path, class: 'plus-dropdown' %>
    <div class="profile-dropdown">
      <% if current_user.avatar.nil? %>
        <%= image_tag "https://avatars2.githubusercontent.com/u/34108893?v=4", class: 'avatar-icon' %>
      <% else %>
        <%= image_tag current_user.avatar, class: 'avatar-icon' %>
      <% end %>
        <div class="dropdown-menu">
          <ul class="dropdown-links">
            <h4>Signed in as</h4>
            <p><%= current_user.username %></p>
            <div class="divider"></div>
            <li><%= link_to 'Your profile', "/#{current_user.username}" %></li>
            <li>Your stars</li>
            <li>Your gists</li>
            <div class="divider"></div>
            <li>Help</li>
            <li>Settings</li>
            <li><%= link_to 'Sign out', logout_path, method: :delete %></li>
          </ul>
        </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <%= render partial: '/layouts/navbar' %>
    <% else %>
      <%= render partial: '/layouts/logged_out_nav' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_followers_tab.html.erb
<ul class='follower-list'>
  <% @profile.followers.each do |follower| %>
    <li class='follower-item'>
      <div class="avatar-thumbnail">
        <%= link_to image_tag(follower.avatar), "/#{follower.login}" %>
      </div>
      <div class="follower-info">
        <%= follower.login %>
      </div>
      <%= button_to 'Follow', "/#{follower.login}" %>
    </li>
  <% end %>
</ul>

app/views/users/_following_tab.html.erb
<ul class='following-list'>
  <% @profile.following.each do |followed| %>
    <li class='following-item'>
      <div class="avatar-thumbnail">
        <%= link_to image_tag(followed.avatar), "/#{followed.login}" %>
      </div>
      <div class="followed-info">
        <%= followed.login %>
      </div>
      <%= button_to 'Follow', "/#{followed.login}" %>
    </li>
  <% end %>
</ul>

app/views/users/_overview_tab.html.erb
<div class="pinned-repos">
  <h4>Pinned repositories</h4>
  <ul class='pinned-grid'>
    <% @profile.pinned_repos.each do |repo| %>
      <li class='pinned-item'>
        <%= link_to repo.name %>
        <% unless repo.description.nil? %>
          <%= repo.description %>
        <% end %>
        <div class="pinned-attributes">
          <% unless repo.language.nil? %>
            dot
            <%= repo.language %>
          <% end %>
          <% unless repo.forks_count.zero? %>
            fork
            <%= repo.forks_count %>
          <% end %>
          <% if repo.updated_at < 1.month.ago %>
            <p>Updated <%= ((Time.current - repo.updated_at) / 1.day).round %> days ago</p>
          <% elsif repo.updated_at < 1.month.ago %>
            <p>Updated on <%= repo.updated_at.strftime('%b %e') %></p>
          <% else %>
            <p>Updated on <%= repo.updated_at.strftime('%b %e, %Y') %></p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="contributions">
  <h4>Contribution activity</h4>
  <ul class='pinned-grid'>
    <% @profile.contributions[0..19].each do |contribution| %>
      <li class='contribution-item'>
        <%= contribution.type %>
        <%= contribution.repo %>
        <%= contribution.created_at %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/_repositories_tab.html.erb
<div class='repo-search'>

</div>
<ul class='repo-list'>
  <% @profile.repos.each do |repo| %>
    <li class='repo-item'>
      <%= link_to repo.name %>
      <% unless repo.description.nil? %>
        <%= repo.description %>
      <% end %>
      <div class="repo-attributes">
        <% unless repo.language.nil? %>
          dot
          <%= repo.language %>
        <% end %>
        <% unless repo.forks_count.zero? %>
          fork
          <%= repo.forks_count %>
        <% end %>
        <% if repo.updated_at < 1.month.ago %>
          <p>Updated <%= ((Time.current - repo.updated_at) / 1.day).round %> days ago</p>
        <% elsif repo.updated_at < 1.month.ago %>
          <p>Updated on <%= repo.updated_at.strftime('%b %e') %></p>
        <% else %>
          <p>Updated on <%= repo.updated_at.strftime('%b %e, %Y') %></p>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/_starred_tab.html.erb
<div class='starred-search'>

</div>
<ul class='starred-list'>
  <% @profile.starred.each do |repo| %>
    <li class='starred-item'>
      <%= link_to @profile.user.login %>/<%= link_to repo.name %>
      <div class="repo-attributes">
        <% unless repo.language.nil? %>
          dot
          <%= repo.language %>
        <% end %>
        <% unless repo.stargazers_count.zero? %>
          fork
          <%= repo.stargazers_count %>
        <% end %>
        <% if repo.updated_at < 1.month.ago %>
          <p>Updated <%= ((Time.current - repo.updated_at) / 1.day).round %> days ago</p>
        <% elsif repo.updated_at < 1.month.ago %>
          <p>Updated on <%= repo.updated_at.strftime('%b %e') %></p>
        <% else %>
          <p>Updated on <%= repo.updated_at.strftime('%b %e, %Y') %></p>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="profile-main">
  <div class="profile-card">
    <% if @profile.user.avatar.nil? %>
      <%= image_tag "https://avatars2.githubusercontent.com/u/34108893?v=4", class: 'avatar' %>
    <% else %>
      <%= image_tag @profile.user.avatar, class: 'avatar'%>
    <% end %>
    <h4 class='profile-name'><%= @profile.user.name %></h4>
    <p class='profile-username'><%= @profile.user.login %></p>
    <% if current_user.uid == @profile.user.uid %>
      <% if @profile.user.bio.nil? %>
        <%= button_to 'Add Bio', '/', class: 'bio-button'%>
      <% else %>
        <%= @profile.user.bio %>
      <% end %>
    <% else %>
      <%= link_to 'Follow', '/' %>
    <% end %>
  </div>
  <main class='profile-body'>
    <div class="profile-links">
      <div class="linko ">
        <%= link_to 'Overview', "/#{@profile.user.login}" %>
      </div>
      <div class="link">
        <%= link_to 'Repositories', "/#{@profile.user.login}?tab=repositories" %>
        <div class="counter">
          <%= @profile.user.public_repos %>
        </div>
      </div>
      <div class="link">
        <%= link_to 'Stars', "/#{@profile.user.login}?tab=stars" %>
        <div class="counter">
          <%= @profile.star_count %>
        </div>
      </div>
      <div class="link">
        <%= link_to 'Followers', "/#{@profile.user.login}?tab=followers" %>
        <div class="counter">
          <%= @profile.user.followers %>
        </div>
      </div>
      <div class="link">
        <%= link_to 'Following', "/#{@profile.user.login}?tab=following" %>
        <div class='counter'>
          <%= @profile.user.following %>
        </div>
      </div>
    </div>
    <section>
      <% case params[:tab] %>
      <% when 'repositories' %>
        <%= render partial: '/users/repositories_tab' %>
      <% when 'stars' %>
        <%= render partial: '/users/starred_tab' %>
      <% when 'followers' %>
        <%= render partial: '/users/followers_tab' %>
      <% when 'following' %>
        <%= render partial: '/users/following_tab' %>
      <% else %>
        <%= render partial: '/users/overview_tab' %>
      <% end %>
    </section>
  </main>
</div>